version: "3"
services:
  frontend:
    build:
      context: ./frontend
    networks:
      - snap
  backend:
    environment:
      TUNEBLADE_HOST: "192.168.1.56:1337"
      SNAPCAST_HOST: "192.168.1.204:1780"
    build:
      context: ./api
    networks:
      - snap
  revproxy:
    build: ./nginx
    networks:
      - snap
    ports:
      - "80:80"
networks:
  snap:
