version: "3"
services:
  frontend:
    build:
      context: ./frontend
      args:
        SNAPCAST_HOST: "192.168.1.204:1780" # replace with resolving name later
    #image: "blade86/snaptune-webui:latest"
    networks:
      - snap
  backend:
    environment:
      TUNEBLADE_HOST: "192.168.1.56:1337"
    build:
      context: ./api
    #image: "snaptune-api:latest"
    networks:
      - snap
  revproxy:
    build: ./nginx
    #image: "blade86/snaptune-proxy:latest"
    networks:
      - snap
    ports:
      - "80:80"
networks:
  snap:
